#!/bin/bash

# pull origin
git pull

# add all changes
git add .

# commit all changes to head
if [ $# > 0 ]
then git commit -m "$0"
else 
	git commit -m "auto-push"
fi

# push all changes to origin
git push -u origin master
