#!/bin/bash
# Script to test for statement 
# display the multiplication table for the given number from command line
# on each row: display num * i (i from 1 to num)
if [ $# -eq 0 ] 
then echo "Error - Number missing from command line argument" 
echo "Syntax : $0 number" 
echo "Use to print multiplication table for given number" 
exit 1 
fi 
n=$1 
for ((i=1; i <=$n; i=i+1))
#for i in `seq 1 1 $1`
do 
echo "$n * $i = `expr $i \* $n`" 
done
