#!/bin/bash 
#Script to test while statement 
echo "please input an integet"
read num
#display the multiplication table for the input number
#on each row: display num * i (i from 1 to 9)
#using expr command to represent arithmetic expression
i=1 
while [ $i -le 9 ] 
do 
     echo "$num * $i = `expr $i \* $num`" 
     i=`expr $i + 1` 
done

